services:
  kong:
    ports: !reset
      - 127.0.0.1:${KONG_HTTP_PORT:-8000}:8000
      - 127.0.0.1:${KONG_HTTPS_PORT:-8443}:8443

  analytics:
    ports: !reset
      - 127.0.0.1:4000:4000

  supavisor:
    ports: !reset
      - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
      - 127.0.0.1:${POOLER_PROXY_PORT_TRANSACTION:-6543}:6543
